### PR TITLE
Python 3.7 Support

### PR DESCRIPTION
**Pull request by DirectXMan12**
An errant `except AttributeError` was swallowing exceptions indicating broken Python 3.7 support for ABCs.  It turns out that the Python 3.7 C ABCs support changes the internals of ABCs a bit, necessitating a different approach to fetching the list of virtual subclasses in certain Python 3.7 installations.

TL;DR: I was doing terrible things based on the location and meatiness of Python's liver, but it got replaced with a bionic one in Python 3.7.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@frozencemetery can you run through the full python-gssapi cross platform test suite with this just to double check I didn't break anything, before I merge and publish a revision?  I've tested on Python 2.7, 3.6, and 3.7 using the normal should_be test suite.

**Comment by frozencemetery** [comment]
Tested on:

- [x] debian stable 2
- [x] debian stable 3 
- [x] el7
- [x] fc29 2
- [x] fc29 3

(debian stable heimdal, MacOS 2, and MacOS 3 not checked because they don't run the suite.)

**Comment by DirectXMan12** [comment]
I'll publish an update to pypi a bit later

**Comment by DirectXMan12** [comment]
Release published: https://pypi.org/manage/project/shouldbe/release/0.1.1/

**Pull request merged**
